// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_Zxfm_rWCeM90XcxM4rIrgRrQPVjoyc',
    appId: '1:35449708033:web:45db5a83a7708b87afaa00',
    messagingSenderId: '35449708033',
    projectId: 'bluechat-c371b',
    authDomain: 'bluechat-c371b.firebaseapp.com',
    storageBucket: 'bluechat-c371b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6HOnPbzS0OR05KVq7NfgoRMui5k2ShI',
    appId: '1:35449708033:android:1e2eab9ef21450b4afaa00',
    messagingSenderId: '35449708033',
    projectId: 'bluechat-c371b',
    storageBucket: 'bluechat-c371b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcclf714QevvF8eIvRZSPO-YwNstgeNBg',
    appId: '1:35449708033:ios:e1c78c72cdf613a2afaa00',
    messagingSenderId: '35449708033',
    projectId: 'bluechat-c371b',
    storageBucket: 'bluechat-c371b.appspot.com',
    iosBundleId: 'com.example.bluechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcclf714QevvF8eIvRZSPO-YwNstgeNBg',
    appId: '1:35449708033:ios:5ad96953fcba59cfafaa00',
    messagingSenderId: '35449708033',
    projectId: 'bluechat-c371b',
    storageBucket: 'bluechat-c371b.appspot.com',
    iosBundleId: 'com.example.bluechat.RunnerTests',
  );
}
